### PR TITLE
Update to SDK 3.3.3

### PR DESCRIPTION
**Pull request by FabienLavocat**
- Use XcFramework
- Voxeet SDK 3.3.3

### CODE REVIEW

**Comment by alok-think** [comment]
please create a branch for Voxeet SDK version3.3.3 to work with Xcode 13.2, I saw currently there is not compatible, also the project is not running in simulator as well. Also please update the Library for Voxeet UXKit and Voxeet SDK to work with Swift 5 and Xcode 13.2

**Review by yganu — APPROVED** [review]
Works for me:
Xcode 13.2.1 and Swift 5

**Comment by FabienLavocat** [comment]
@alok-think this Pull Request will bring the support for the Voxeet SDK 3.3.3 into the repo.
Voxeet [SDK 3.3.3](https://github.com/voxeet/voxeet-sdk-ios/releases/tag/3.3.3) is compatible with Xcode 13.2.1. And the[ UXKit 1.6.4 ](https://github.com/voxeet/voxeet-uxkit-ios/releases/tag/1.6.4)is using the SDK 3.3.3 so it is already compatible with the latest Xcode.
The support for Xcode 13.2 was brought by the [SDK 3.3.1](https://github.com/voxeet/voxeet-sdk-ios/releases/tag/v3.3.1).

**Comment by alok-think** [comment]
> @alok-think this Pull Request will bring the support for the Voxeet SDK 3.3.3 into the repo. Voxeet [SDK 3.3.3](https://github.com/voxeet/voxeet-sdk-ios/releases/tag/3.3.3) is compatible with Xcode 13.2.1. And the[ UXKit 1.6.4 ](https://github.com/voxeet/voxeet-uxkit-ios/releases/tag/1.6.4)is using the SDK 3.3.3 so it is already compatible with the latest Xcode. The support for Xcode 13.2 was brought by the [SDK 3.3.1](https://github.com/voxeet/voxeet-sdk-ios/releases/tag/v3.3.1).

Hi Sir, Voxeet SDk 3.3.3 is working fine now in your sample project, VoxeetUIKit is not working in your sample project, kindly provide me both SDKs (VOXEET UIKIT and VoxeetSDK) that will work in Xcode 13.2 with Swift 5.

Thank you. 

Please provide any sample project source code, or link, so that we build.
Also please make sure that other library will work with other pod libraries as well, like 

pod "SCPageControl"
pod "LCBannerView"
pod 'SDWebImage'
pod 'GoogleMaps'
pod 'GooglePlaces'
pod "GooglePlacesSearchController"
pod 'GooglePlacePicker'
pod 'IQKeyboardManagerSwift'
pod 'Alamofire','~> 4.0'
pod 'SVProgressHUD'
#pod 'GoogleSignIn'   ##Not Used
pod 'FBSDKCoreKit'
#pod 'FBSDKLoginKit'  ##Not Used
#pod 'ACFloatingTextfield-Swift' ##Not Used
pod 'SwiftSoup'
pod 'AARatingBar'
pod 'FacebookShare'
pod 'AZSClient'
pod 'NextGrowingTextView'
pod 'SRSwiftyPopView'
pod "Atributika"
pod 'CameraManager', '~> 5.1'
pod 'Firebase/Analytics'
pod 'Firebase/DynamicLinks'

I had used all libraries in my project and that is all really very important to implement,  if any library is not supported, kindly provide me with alternative libraries and solutions. 

Screenshot 2022-02-17 at 9 19 16 AM

**Comment by alok-think** [comment]
HI, I was facing another issue in My Project, I installed VoxeetSDK using Swift Package Manager and it is successfully installed when I build and compiled the project, I got pop-up "Build Failed" but there will be no issue in project inspector. 
please refer to the screenshot. 
I wish to use both VoxeetUxKit and VoxeetSDK. 

Also, I find that VoxeetUXKit is not able to install because of your GitHub source, Package.Swift file is missing for https://github.com/voxeet/voxeet-uxkit-ios/
But for VoxeetSDK (Package.swift file) is available  https://github.com/voxeet/voxeet-sdk-ios

Kindly check above both links, maybe it can be true, I m not sure about this. but XCode pops up this error message that Package.Swift not found for https://github.com/voxeet/voxeet-uxkit-ios/ Library. When i installed this using Swift Package Manager. 

No Issue

**Comment by alok-think** [comment]
Please also check the issue : Installing VoxeetSDK and VoseetUXKit with Swift Package Manager #30
https://github.com/voxeet/voxeet-uxkit-ios/issues/30

**Comment by FabienLavocat** [comment]
@alok-think Our UXKit for iOS is not currently supporting Apple Package Manager. We are working on it, see https://github.com/voxeet/voxeet-uxkit-ios/pull/37.
For the compilation error you are having, please make sure you have Bitcode disabled for your project. I will merge this pull request and close the thread. In the meantime, if you have any problems, please create an issue in the appropriate GitHub repository.

**Pull request merged**
